config/routes.rb
Rails.application.routes.draw do
  get 'static/inicio'

  get 'static/precios'

  devise_for :users
  resources :buildings do
    resources :employees
    resources :apartments do
      resources :owners
    end
    resources :people
  end

  root 'static#inicio' #Siempre debe ir de ultimo
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :person
  belongs_to :apartment
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @building = current_user.buildings.find(params[:building_id])
    @apartment = @building.apartments.find(params[:apartment_id])
    @owners = @apartment.owners.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @building = current_user.buildings.find(params[:building_id])
    @apartment = @building.apartments.find(params[:apartment_id])
    @owner = @apartment.owners.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @building = current_user.buildings.find(params[:building_id])
    @apartment = @building.apartments.find(params[:apartment_id])
    @owner = @apartment.owners.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to building_apartment_owner_path(@building, @apartment, @owner), notice: 'El propietario fue adicionado satisfactoriamente' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to building_apartment_owner_path(@building, @apartment, @owner), notice: 'El propietario fue modificado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to building_apartment_owners_path(@building, @apartment), notice: 'El propietario fue borrado satisfactoriamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @building = current_user.buildings.find(params[:building_id])
      @apartment = @building.apartments.find(params[:apartment_id])
      @owner = @apartment.owners.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:person_id, :fecha_inicio, :fecha_fin, :activo)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= form_for([@building, @apartment, owner]) do |f| %>
  <% if owner.errors.any? %>
    <div id="error_explanation">
      <h2>No se pudo guardar el propietario</h2>

      <ul>
      <% owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id, 'Persona' %>
    <%= f.collection_select :person_id, @building.people, :id, :nombre %>
  </div>

  <div class="field">
    <%= f.label :fecha_inicio %>
    <%= f.date_select :fecha_inicio %>
  </div>

  <div class="field">
    <%= f.label :fecha_fin %>
    <%= f.date_select :fecha_fin %>
  </div>

  <div class="field">
    <%= f.label :activo %>
    <%= f.check_box :activo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editar propietario</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Ver', building_apartment_owner_path(@building, @apartment, @owner)%> |
<%= link_to 'Atras', building_apartment_path(@building, @apartment) %>

app/views/owners/index.html.erb
<h1>Dueños de apartamento <%= @apartment.nombre %></h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Fecha inicio</th>
      <th>Fecha fin</th>
      <th>Activo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.person.nombre%></td>
        <td><%= owner.fecha_inicio %></td>
        <td><%= owner.fecha_fin %></td>
        <td><%= owner.activo ? 'Si': 'No'  %></td>
        <td><%= link_to 'Ver', building_apartment_owner_path(@building, @apartment, Owner) %></td>
        <td><%= link_to 'Editar', edit_building_apartment_owner_path(@building, @apartment, owner) %></td>
        <td><%= link_to 'Eliminar', building_apartment_owner_path(@building, @apartment, Owner), method: :delete, data: { confirm: 'Estas Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Propietario', new_building_apartment_owner_path(@building, @apartment) %>

app/views/owners/new.html.erb
<h1>Nuevo propietario</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Atras', building_apartment_path(@building, @apartment) %>

app/views/owners/show.html.erb
<p>
  <strong>Person:</strong>
  <%= @owner.person %>
</p>

<p>
  <strong>Apartment:</strong>
  <%= @owner.apartment.nombre %>
</p>

<p>
  <strong>Fecha inicio:</strong>
  <%= @owner.fecha_inicio %>
</p>

<p>
  <strong>Fecha fin:</strong>
  <%= @owner.fecha_fin %>
</p>

<p>
  <strong>Activo:</strong>
  <%= @owner.activo %>
</p>

<%= link_to 'Editar', edit_building_apartment_owner_path(@building, @apartment, @owner) %> |
<%= link_to 'Atras', building_apartment_path(@building, @apartment) %>