config/routes.rb
Rails.application.routes.draw do
  get 'static/inicio'

  get 'static/precios'

  devise_for :users
  resources :buildings do
    resources :employees
    resources :apartments do
      resources :owners
    end
    resources :people
  end

  root 'static#inicio' #Siempre debe ir de ultimo
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :user
  has_many :employee
  has_many :apartments
  has_many :people

  validates :nit, presence: {message: 'No puede estar en blanco'}
  validates :nombre, presence: {message: 'No puede estar en blanco'}
  validates_presence_of :telefono, message: 'No puede estar en blanco'

  def nombre_completo
    return "#{nombre}, #{nit}"
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_building, only: [:show, :edit, :update, :destroy] #Macro

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = current_user.buildings
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = current_user.buildings.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = current_user.buildings.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Unidad Residencial creada atisfactoriamente' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Unidad residencial modificada correctamente' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Unidad residencial borrada satisfactoriamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = current_user.buildings.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:nit, :nombre, :telefono, :direccion, :activo)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_for(building, html: {class: 'form-horizontal'}) do |f| %>
  <% if building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(building.errors.count, "Error") %> No se pudo guardar la Unidad Residenciál:</h2>
      <ul>
      <% building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nit, 'NIT', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :nit, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :nombre, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :nombre, class: 'form-control'  %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :telefono, 'Teléfono', class: 'col-sm-2 control-label'  %>
    <div class="col-sm-10">
      <%= f.text_field :telefono, class: 'form-control'  %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :direccion, 'Dirección', class: 'col-sm-2 control-label'  %>
    <div class="col-sm-10">
      <%= f.text_field :direccion, class: 'form-control'  %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
          <%= f.label :activo do %>
            <%= f.check_box :activo %>Activo
          <% end %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Aceptar', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editar Unidad Residencial</h1>

<%= render 'form', building: @building %>

<%= link_to 'Visualizar', @building %> |
<%= link_to 'Atras', buildings_path %>

app/views/buildings/index.html.erb
<div class="page-header">
  <h1><i class="fa fa-bank page-header-icon"></i>&nbsp;&nbsp;Administración de Unidades Residenciales</h1>
  <div class="pull-right col-xs-12 col-sm-auto">
    <%= link_to '<i class="fa fa-plus"></i> Nueva Unidad'.html_safe, new_building_path, class: 'btn btn-success btn-lg btn-labeled pull-right'%>
  </div>
</div> <!-- / .page-header -->
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info panel-dark widget-profile">
      <div class="panel-heading">
        <div class="widget-profile-bg-icon"><i class="fa fa-home"></i></div>
        <%= image_tag 'building.jpg', class: 'widget-profile-avatar' %>
        <div class="widget-profile-header">
          <span>Listado de Unidades Residenciales</span><br>
          <%= current_user.nombre %>
        </div>
      </div> <!-- / .panel-heading -->

      <div class="panel">
        <div class="panel-body">
          <div class="table-info">
            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="jq-datatables-example">
              <thead>
                <tr>
                  <th>Nombre Completo</th>
                  <th>NIT</th>
                  <th>Nombre</th>
                  <th>Teléfono</th>
                  <th>Dirección</th>
                  <th>Activo</th>
                  <th></th>
                </tr>
              </thead>

              <tbody>
                <% @buildings.each do |building| %>
                  <tr>
                    <td><%= building.nombre_completo %></td>
                    <td><%= building.nit %></td>
                    <td data-container="body" data-toggle="popover" data-placement="bottom" data-content="<%= building.employee.map(&:nombre).join(', ') %>">
                        <%= building.nombre %>
                    </td>
                    <td><%= building.telefono %></td>
                    <td><%= building.direccion %></td>
                    <td>
                      <% if building.activo %>
                          <span class="label label-success">Si</span>
                      <% else %>
                          <span class="label label-danger">No</span>
                      <% end %>
                    </td>
                    <td>
                      <div class="btn-group" >
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><i class="fa fa-caret-down"></i>&nbsp;&nbsp;Opciones</button>
                        <ul class="dropdown-menu" style="z-index: 100 !important;">
                          <li><%= link_to 'Ver', building %></li>
                          <li><%= link_to 'Editar', edit_building_path(building) %></li>
                          <li><%= link_to 'Borrar', building, method: :delete, data: { confirm: 'Seguro que quiere borrar?' } %></li>
                        </ul>
                      </div>&nbsp;
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    document.addEventListener("turbolinks:load", function()
    {
        var init = [];

        init.push(function () {
            $('#jq-datatables-example').dataTable();
            $('#jq-datatables-example_wrapper .table-caption').text('Unidades');
            $('#jq-datatables-example_wrapper .dataTables_filter input').attr('placeholder', 'Buscar...');
        });

        window.PixelAdmin.start(init);
    });
</script>

app/views/buildings/new.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h3><%= link_to '<<', buildings_path, class: 'btn btn-info'%>&nbsp;&nbsp;Crear Unidad Residencial</h3>
  </div>
  <div class="panel-body">
    <%= render 'form', building: @building %>
  </div>
</div>

app/views/buildings/show.html.erb
<div class="panel">
  <div class="panel-heading">
    <span class="panel-title"><h3>Datos Unidad Residencial <%= @building.nombre_completo %></h3></span>
  </div>
  <div class="panel-body">
    <ul id="uidemo-tabs-default-demo" class="nav nav-tabs">
      <li class="active">
        <a href="#uidemo-tabs-unidad" data-toggle="tab">Unidad</a>
      </li>
      <li class="">
        <a href="#uidemo-tabs-empleados" data-toggle="tab">Empleados</a>
      </li>
    </ul>

    <div class="tab-content tab-content-bordered">
      <div class="tab-pane fade active in" id="uidemo-tabs-unidad">
        <br>
        <div class="profile-full-name">
          <span class="text-semibold"><i class="fa fa-bank page-header-icon"></i>&nbsp;Datos Unidad Residencial</span>
        </div>
        <div class="profile-row">
          <div class="left-col">
            <div class="profile-block">
              <div class="panel profile-photo">
                <%= image_tag 'building.jpg' %>
              </div>
            </div>
          </div>
          <div class="right-col">
            <hr class="profile-content-hr no-grid-gutter-h">
            <div class="profile-content">
              <div class="panel">
                <br>
                <form id="form_vehiculo">
                  <div class="form-group">
                    <label for="jq-validation-url" class="col-sm-3 control-label"><strong>Nombre Completo:</strong></label>
                    <div class="col-sm-9">
                      <label for="jq-validation-url" class="col-sm-9 control-label"><%= @building.nombre_completo %></label>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="jq-validation-url" class="col-sm-3 control-label"><strong>NIT:</strong></label>
                    <div class="col-sm-9">
                      <label for="jq-validation-url" class="col-sm-9 control-label"><%= @building.nit %></label>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="jq-validation-url" class="col-sm-3 control-label"><strong>Nombre:</strong></label>
                    <div class="col-sm-9">
                      <label for="jq-validation-url" class="col-sm-9 control-label"><%= @building.nombre %></label>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="jq-validation-url" class="col-sm-3 control-label"><strong>Teléfono:</strong></label>
                    <div class="col-sm-9">
                      <label for="jq-validation-url" class="col-sm-9 control-label"><%= @building.telefono %></label>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="jq-validation-url" class="col-sm-3 control-label"><strong>Dirección:</strong></label>
                    <div class="col-sm-9">
                      <label for="jq-validation-url" class="col-sm-9 control-label"><%= @building.direccion %></label>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="jq-validation-url" class="col-sm-3 control-label"><strong>Activo:</strong></label>
                    <div class="col-sm-9">
                      <% if @building.activo %>
                          <label for="jq-validation-url" class="col-sm-9 control-label">Si</label>
                      <% else %>
                          <label for="jq-validation-url" class="col-sm-9 control-label">No</label>
                      <% end %>
                    </div>
                  </div>
                  <br>
                  <div class="form-group">
                    <%= link_to 'Editar', edit_building_path(@building), class: 'btn btn-large btn-success col-sm-2', style: 'margin-left: 10px' %>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>

      </div> <!-- / .tab-pane -->
      <div class="tab-pane fade" id="uidemo-tabs-empleados">
        <div class="row">
          <div class="col-md-12">
            <div class="panel panel-info panel-dark widget-profile">
              <div class="panel-heading">
                <div class="widget-profile-bg-icon"><i class="fa fa-user"></i></div>
                <%= image_tag 'building.jpg', class: 'widget-profile-avatar' %>
                <div class="widget-profile-header">
                  <span>Listado de Empleados</span><br>
                  <%= @building.nombre_completo %>
                </div>
              </div> <!-- / .panel-heading -->

              <div class="panel">
                <div class="panel-body">
                  <div class="table-info">
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="jq-datatables-example">
                      <thead>
                      <tr>
                        <th>Cédula</th>
                        <th>Nombre</th>
                        <th>Cargo</th>
                      </tr>
                      </thead>

                      <tbody>
                      <% @building.employee.each do |employee| %>
                          <tr>
                            <td><%= link_to employee.cedula, building_employee_path(@building, employee) %></td>
                            <td><%= link_to employee.nombre, building_employee_path(@building, employee) %></td>
                            <td><%= link_to employee.cargo, building_employee_path(@building, employee) if employee.cargo.present? %></td>
                          </tr>
                      <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>


      </div> <!-- / .tab-pane -->
    </div> <!-- / .tab-content -->
  </div>
</div>

<script type="text/javascript">
  document.addEventListener("turbolinks:load", function()
  {
    var init = [];

    init.push(function ()
    {
        $('body').addClass("page-profile");
    });

    init.push(function ()
    {
        $('#jq-datatables-example').dataTable();
        $('#jq-datatables-example_wrapper .table-caption').text('Empleados');
        $('#jq-datatables-example_wrapper .dataTables_filter input').attr('placeholder', 'Buscar...');
    });

    window.PixelAdmin.start(init);
  });
</script>