config/routes.rb
Rails.application.routes.draw do
  get 'static/inicio'

  get 'static/precios'

  devise_for :users
  resources :buildings do
    resources :employees
    resources :apartments do
      resources :owners
    end
    resources :people
  end

  root 'static#inicio' #Siempre debe ir de ultimo
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :building
  has_many :owners
  has_many :people, through: :owners
  validates_presence_of :nombre, message: 'No puede estar en blanco'
  validates :tipo, numericality: {only_integer: true,
                                  greater_than_or_equal_to: 1,
                                  less_than_or_equal_to: 4,
                                  message: 'Debes seleccionarlo correctamente'}

  TIPO = {1 =>'Apartamento', 2=>'Parquedero', 3=>'San Alejo', 4=>'Local'}

  def nombre_tipo
    Apartment::TIPO[self.tipo]
  end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    @building = current_user.buildings.find(params[:building_id])
    @apartments = @building.apartments.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @building = current_user.buildings.find(params[:building_id])
    @apartment = @building.apartments.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @building = current_user.buildings.find(params[:building_id])
    @apartment = @building.apartments.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to building_apartment_path(@building, @apartment), notice: 'El Apartamento fue creado Satisfactoriamente' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to building_apartment_path(@building, @apartment), notice: 'El Apartamento fue modificado Satisfactoriamente' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to building_apartments_path(@building), notice: 'El Apartamento fue borrado Satisfactoriamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @building = current_user.buildings.find(params[:building_id])
      @apartment = @building.apartments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:nombre, :matricula, :area, :coeficiente, :tipo)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<%= form_for([@building, apartment]) do |f| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> No se pudo guardar el Apartamento :</h2>
      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :matricula %>
    <%= f.text_field :matricula %>
  </div>

  <div class="field">
    <%= f.label :area %>
    <%= f.text_field :area %>
  </div>

  <div class="field">
    <%= f.label :coeficiente %>
    <%= f.text_field :coeficiente %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.select(:tipo, Apartment::TIPO.collect {|k,v| [v,k]}) %>
  </div>

  <div class="actions">
    <%= f.submit 'Aceptar' %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editar apartamento</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Ver', building_apartment_path(@building, @apartment) %> |
<%= link_to 'Atrás', building_apartments_path(@building) %>

app/views/apartments/index.html.erb
<h1>Lista de Apartamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Matrícula</th>
      <th>Área</th>
      <th>Coeficiente</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.nombre %></td>
        <td><%= apartment.matricula %></td>
        <td><%= apartment.area %></td>
        <td><%= apartment.coeficiente %></td>
        <td><%= apartment.nombre_tipo %></td>
        <td><%= link_to 'Ver', building_apartment_path(@building, apartment) %></td>
        <td><%= link_to 'Editar', edit_building_apartment_path(@building, apartment) %></td>
        <td><%= link_to 'Borrar', building_apartment_path(@building, apartment), method: :delete, data: { confirm: 'Esta Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Apartamento', new_building_apartment_path(@building) %>

app/views/apartments/new.html.erb
<h1>Nuevo apartamento</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Atras', building_apartments_path(@building) %>

app/views/apartments/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @apartment.nombre %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @apartment.matricula %>
</p>

<p>
  <strong>Area:</strong>
  <%= @apartment.area %>
</p>

<p>
  <strong>Coeficiente:</strong>
  <%= @apartment.coeficiente %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @apartment.nombre_tipo %>
</p>
<p>
  <strong>Unidad Residencial:</strong>
  <%= @apartment.building.nombre_completo %>
</p>

<%= link_to 'Editar', edit_building_apartment_path(@building, @apartment) %> |
<%= link_to 'Atrás', building_apartments_path(@building) %>

<h3>
  Propietarios
</h3>

<h1>Dueños de apartamento <%= @apartment.nombre %></h1>

<table>
  <thead>
  <tr>
    <th>Person</th>
    <th>Fecha inicio</th>
    <th>Fecha fin</th>
    <th>Activo</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @apartment.owners.each do |owner| %>
      <tr>
        <td><%= owner.person.nombre%></td>
        <td><%= owner.fecha_inicio %></td>
        <td><%= owner.fecha_fin %></td>
        <td><%= owner.activo ? 'Si': 'No'  %></td>
        <td><%= link_to 'Ver', building_apartment_owner_path(@building, @apartment, Owner) %></td>
        <td><%= link_to 'Editar', edit_building_apartment_owner_path(@building, @apartment, owner) %></td>
        <td><%= link_to 'Eliminar', building_apartment_owner_path(@building, @apartment, Owner), method: :delete, data: { confirm: 'Estas Seguro?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Propietario', new_building_apartment_owner_path(@building, @apartment) %>