config/routes.rb
Rails.application.routes.draw do
  get 'static/inicio'

  get 'static/precios'

  devise_for :users
  resources :buildings do
    resources :employees
    resources :apartments do
      resources :owners
    end
    resources :people
  end

  root 'static#inicio' #Siempre debe ir de ultimo
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to image_tag('edificio', style: 'width: 50px; margin-top: -15px; margin-left: -15px;'), buildings_path, class: 'navbar-brand' %>
    </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <% if @building.present? && @building.persisted? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Empleados <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Lista completa de Empleados', building_employees_path(@building) %></li>
                    <li><%= link_to 'Agregar Empleado', new_building_employee_path(@building) %></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Apartamentos <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Lista de Apartamentos', building_apartments_path(@building) %></li>
                    <li><%= link_to 'Agregar Apartamento', new_building_apartment_path(@building) %></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Personas <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <%= link_to 'Lista de Personas', building_people_path(@building) %>
                    <%= link_to 'Agregar Personas', new_building_person_path(@building) %>
                  </ul>
                </li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to current_user.nombre, edit_user_registration_path %>
            </li>
            <li>
              <%= link_to('Salir', destroy_user_session_path, :method => :delete) %>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav">
            <li><%= link_to 'Inicio', root_path %></li>
            <li><%= link_to 'Precios', static_precios_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Iniciar Sesión', new_user_session_path %></li>
          </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">
    <title>Unidades Residenciales</title>
    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    --><!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>

    <!--<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>-->

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'pixel-admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'widgets', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'rtl', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'themes', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'pages', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'jquery', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'bootstrap', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'pixel-admin', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery-ui-extras', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery.mockjax', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'bootstrap-editable-demo', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified JavaScript -->
    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>-->
  </head>
  <body class="theme-default main-menu-animated">
  <% if user_signed_in? && @building.present? && @building.persisted? %>
    <div id="main-wrapper">
  <% end %>
      <div id="main-navbar" class="navbar navbar-inverse" role="navigation">
        <!-- Main menu toggle -->
        <button type="button" id="main-menu-toggle">
          <i class="navbar-icon fa fa-bars icon"></i>
          <span class="hide-menu-text">HIDE MENU</span>
        </button>
        <div class="navbar-inner">
          <!-- Main navbar header -->
          <div class="navbar-header">
            <!-- Logo -->
            <div>
              <%= link_to image_tag('edificio.png', style: 'width: 47px; margin-left: -15px;'), buildings_path, class: 'navbar-brand' %>
            </div>
          </div> <!-- / .navbar-header -->
          <div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
            <div class="right clearfix">
              <ul class="nav navbar-nav pull-right right-navbar-nav">
                <% if user_signed_in? %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
                      <i class="navbar-icon fa fa-chevron-down icon"></i>
                      <span>Opciones</span>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to '<i class="menu-icon fa fa-undo"></i> Inicio'.html_safe, root_path %></li>
                      <li><%= link_to '<i class="menu-icon fa fa-dollar"></i> Precios'.html_safe, static_precios_path %></li>
                      <li><%= link_to '<i class="menu-icon fa fa-user"></i> Perfil'.html_safe, edit_user_registration_path %></li>
                      <li class="divider"></li>
                      <li><%= link_to '<i class="menu-icon fa fa-power-off"></i> Salir'.html_safe, destroy_user_session_path, :method => :delete %></li>
                    </ul>
                  </li>
                <% else %>
                    <li><%= link_to '<i class="menu-icon fa fa-undo"></i> Inicio'.html_safe, root_path %></li>
                    <li><%= link_to '<i class="menu-icon fa fa-dollar"></i> Precios'.html_safe, static_precios_path %></li>
                    <li><%= link_to '<i class="menu-icon fa fa-user"></i> Iniciar Sesión'.html_safe, new_user_session_path %></li>
                <% end %>
              </ul>
            </div>
          </div> <!-- / #main-navbar-collapse -->
        </div> <!-- / .navbar-inner -->
      </div> <!-- / #main-navbar -->

      <% if user_signed_in? && @building.present? && @building.persisted? %>
        <div id="main-menu" role="navigation">
          <div id="main-menu-inner">
            <div class="menu-content top" id="menu-content-demo">
              <div>
                <div class="text-bg">
                  <span class="text-slim">Bienvenido</span><br>
                  <span><%= current_user.nombre %></span>
                </div>
                <%= image_tag 'user.png' %>
              </div>
            </div>
            <ul class="navigation">
              <li><%= link_to '<i class="menu-icon fa fa-user"></i><span class="mm-text">Empleados</span>'.html_safe, building_employees_path(@building) %></li>
              <li><%= link_to '<i class="menu-icon fa fa-bank"></i><span class="mm-text">Apartamentos</span>'.html_safe, building_apartments_path(@building) %></li>
              <li><%= link_to '<i class="menu-icon fa fa-group"></i><span class="mm-text">Personas</span>'.html_safe, building_people_path(@building) %></li>
              <li><%= link_to '<i class="menu-icon fa fa-power-off"></i><span class="mm-text">Salir</span>'.html_safe, destroy_user_session_path, :method => :delete %></li>
            </ul>
          </div>
        </div>
      <% end %>
      <!-- /3. $MENU PRINCIPAL ------------------------------------------------------------------------------------------------->
      <div id="content-wrapper">
        <%= yield %>
      </div>
      <% if user_signed_in? && @building.present? && @building.persisted?%>
        <!-- / #content-wrapper -->
        <div id="main-menu-bg"> </div>
        
      <% end %>

    </div>
  </body>
</html>